services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: boilerplate_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - boilerplate_db_data:/var/lib/postgresql/data
    networks:
      - boilerplate_network

networks:
  boilerplate_network:

volumes:
  boilerplate_db_data:
